#include "xpc_internal.h"
#include "xpc.h"
#ifdef XPC_ACTIVITY_ALLOW_BATTERY
#undef XPC_ACTIVITY_ALLOW_BATTERY
#endif
#ifdef XPC_ACTIVITY_DELAY
#undef XPC_ACTIVITY_DELAY
#endif
#ifdef XPC_ACTIVITY_GRACE_PERIOD
#undef XPC_ACTIVITY_GRACE_PERIOD
#endif
#ifdef XPC_ACTIVITY_INTERVAL
#undef XPC_ACTIVITY_INTERVAL
#endif
#ifdef XPC_ACTIVITY_INTERVAL_15_MIN
#undef XPC_ACTIVITY_INTERVAL_15_MIN
#endif
#ifdef XPC_ACTIVITY_INTERVAL_1_DAY
#undef XPC_ACTIVITY_INTERVAL_1_DAY
#endif
#ifdef XPC_ACTIVITY_INTERVAL_1_HOUR
#undef XPC_ACTIVITY_INTERVAL_1_HOUR
#endif
#ifdef XPC_ACTIVITY_INTERVAL_1_MIN
#undef XPC_ACTIVITY_INTERVAL_1_MIN
#endif
#ifdef XPC_ACTIVITY_INTERVAL_30_MIN
#undef XPC_ACTIVITY_INTERVAL_30_MIN
#endif
#ifdef XPC_ACTIVITY_INTERVAL_4_HOURS
#undef XPC_ACTIVITY_INTERVAL_4_HOURS
#endif
#ifdef XPC_ACTIVITY_INTERVAL_5_MIN
#undef XPC_ACTIVITY_INTERVAL_5_MIN
#endif
#ifdef XPC_ACTIVITY_INTERVAL_7_DAYS
#undef XPC_ACTIVITY_INTERVAL_7_DAYS
#endif
#ifdef XPC_ACTIVITY_INTERVAL_8_HOURS
#undef XPC_ACTIVITY_INTERVAL_8_HOURS
#endif
#ifdef XPC_ACTIVITY_PREVENT_DEVICE_SLEEP
#undef XPC_ACTIVITY_PREVENT_DEVICE_SLEEP
#endif
#ifdef XPC_ACTIVITY_PRIORITY
#undef XPC_ACTIVITY_PRIORITY
#endif
#ifdef XPC_ACTIVITY_PRIORITY_MAINTENANCE
#undef XPC_ACTIVITY_PRIORITY_MAINTENANCE
#endif
#ifdef XPC_ACTIVITY_PRIORITY_UTILITY
#undef XPC_ACTIVITY_PRIORITY_UTILITY
#endif
#ifdef XPC_ACTIVITY_REPEATING
#undef XPC_ACTIVITY_REPEATING
#endif
#ifdef XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP
#undef XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP
#endif

const char *XPC_ACTIVITY_ALLOW_BATTERY = "XPC_ACTIVITY_ALLOW_BATTERY";
const char *XPC_ACTIVITY_DELAY = "XPC_ACTIVITY_DELAY";
const char *XPC_ACTIVITY_GRACE_PERIOD = "XPC_ACTIVITY_GRACE_PERIOD";
const char *XPC_ACTIVITY_INTERVAL = "XPC_ACTIVITY_INTERVAL";
const char *XPC_ACTIVITY_INTERVAL_15_MIN = "XPC_ACTIVITY_INTERVAL_15_MIN";
const char *XPC_ACTIVITY_INTERVAL_1_DAY = "XPC_ACTIVITY_INTERVAL_1_DAY";
const char *XPC_ACTIVITY_INTERVAL_1_HOUR = "XPC_ACTIVITY_INTERVAL_1_HOUR";
const char *XPC_ACTIVITY_INTERVAL_1_MIN = "XPC_ACTIVITY_INTERVAL_1_MIN";
const char *XPC_ACTIVITY_INTERVAL_30_MIN = "XPC_ACTIVITY_INTERVAL_30_MIN";
const char *XPC_ACTIVITY_INTERVAL_4_HOURS = "XPC_ACTIVITY_INTERVAL_4_HOURS";
const char *XPC_ACTIVITY_INTERVAL_5_MIN = "XPC_ACTIVITY_INTERVAL_5_MIN";
const char *XPC_ACTIVITY_INTERVAL_7_DAYS = "XPC_ACTIVITY_INTERVAL_7_DAYS";
const char *XPC_ACTIVITY_INTERVAL_8_HOURS = "XPC_ACTIVITY_INTERVAL_8_HOURS";
const char *XPC_ACTIVITY_PREVENT_DEVICE_SLEEP = "XPC_ACTIVITY_PREVENT_DEVICE_SLEEP";
const char *XPC_ACTIVITY_PRIORITY = "XPC_ACTIVITY_PRIORITY";
const char *XPC_ACTIVITY_PRIORITY_MAINTENANCE = "XPC_ACTIVITY_PRIORITY_MAINTENANCE";
const char *XPC_ACTIVITY_PRIORITY_UTILITY = "XPC_ACTIVITY_PRIORITY_UTILITY";
const char *XPC_ACTIVITY_REPEATING = "XPC_ACTIVITY_REPEATING";
const char *XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP = "XPC_ACTIVITY_REQUIRE_SCREEN_SLEEP";
